sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t jtjohny/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jtjohny/docker-react npm run test
